version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./server
    command: npm run start
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/beacon
    depends_on:
      - mongo
  frontend:
    build: ./client
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
volumes:
  mongo-data:
